version: '3'

networks:
  ideaslab-dev:

volumes:
  cache:

services:
  cache:
    container_name: ideaslab-dev-cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - ideaslab-dev
    volumes:
      - cache:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  nginx:
    container_name: ideaslab-dev-nginx
    image: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - main
    networks:
      - ideaslab-dev

  main:
    container_name: ideaslab-dev-main
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./apps/server/.env
      - ./apps/web/.env
      - ./packages/db/.env
    volumes:
      - ./apps/server/src:/app/apps/server/src
      - ./apps/web/src:/app/apps/web/src
      - ./packages/db/src:/app/packages/db/src
      - ./packages/validator/src:/app/packages/validator/src
    networks:
      - ideaslab-dev
    depends_on:
      - cache
