FROM node:16

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY .yarnrc.yml ./
COPY .yarn/ ./.yarn/

COPY apps/server/package.json ./apps/server/package.json

COPY packages/ ./packages/

RUN yarn install

COPY . .

CMD ["yarn", "start"]